from map import Map
from hub import Hub


class Pathfinding():
    """
    Find and build efficient paths through the drone network.
    The pathfinding algorithm calculates the minimum movement cost from
    the start hub to the end hub and keeps all paths with the same minimum
    cost. It can also generate alternative paths with a cost up to two
    turns higher, allowing the simulation to distribute drones more
    efficiently across the available routes.
    """

    def __init__(self, map: Map):
        """
        Initialize the pathfinding system.
        Args:
            map: Map containing the hubs and connections of the network.
        """
        self.map = map

    def reverse_paths(self, inverted_paths):
        """
        Reverse paths generated from the destination to the start.
        Args:
            inverted_paths: List of paths ordered from the end hub
                towards the start hub.
        Returns:
            A list of paths ordered from the start hub towards the
            end hub.
        """
        paths = []
        for path in inverted_paths:
            path.reverse()
            paths.append(path)
        return paths

    def count_priority_hubs(self, path: list[Hub]) -> int:
        """
        Count the priority hubs contained in a path.
        Args:
            path: List of hubs forming a route through the network.
        Returns:
            The number of priority hubs in the path.
        """
        priority_count = 0
        for hub in path:
            if hub.zone_type == "priority":
                priority_count += 1
        return priority_count

    def build_alternative_paths(self, minimum_cost):
        """
        Build paths whose cost is slightly higher than the minimum.
        This method explores the network without revisiting hubs and
        collects paths whose total cost is greater than the minimum
        cost and no more than two turns above it.
        Args:
            minimum_cost: Minimum movement cost found by the pathfinding
                algorithm.
        Returns:
            A list of tuples containing an alternative path and its
            total movement cost.
        """
        alternative_paths = []
        pending = []
        current = self.map.get_start_hub()
        pending.append(([current], 0))
        while pending:
            path, current_cost = pending.pop()
            if path[-1] == self.map.get_end_hub():
                if minimum_cost < current_cost <= minimum_cost + 2:
                    alternative_paths.append((path, current_cost))
                continue
            current = path[-1]
            neighbours = current.get_accessible_hubs()
            for neighbour in neighbours:
                step_cost = 0
                if neighbour in path:
                    continue
                if neighbour.zone_type == "normal" or neighbour.zone_type == "priority":
                    step_cost = 1
                elif neighbour.zone_type == "restricted":
                    step_cost = 2
                new_cost = current_cost + step_cost
                if new_cost > minimum_cost + 2:
                    continue
                new_path = path[:]
                new_path.append(neighbour)
                pending.append((new_path, new_cost))
        return alternative_paths


    def build_paths(self, previous):
        """
        Reconstruct all minimum-cost paths from predecessor information.
        The predecessor dictionary is generated by the shortest-path
        algorithm and may contain multiple predecessors when several
        routes have the same minimum cost.
        Args:
            previous: Dictionary mapping each hub name to its possible
                predecessor hubs.
        Returns:
            A list of paths ordered from the end hub towards the start hub.
        """
        paths = []
        pending = []
        current = self.map.get_end_hub()
        pending.append([current])
        while pending:
            path = pending.pop()
            if path[-1] == self.map.get_start_hub():
                paths.append(path)
                continue
            current = path[-1]
            previous_hubs = previous[current.name]
            if len(previous_hubs) == 1:
                path.append(previous_hubs[0])
                pending.append(path)
            if len(previous_hubs) > 1:
                for previous_hub in previous_hubs:
                    new_path = path[:]
                    new_path.append(previous_hub)
                    pending.append(new_path)
        return paths


    def find_path(self):
        """
        Find the minimum movement cost and all corresponding paths.
        The algorithm calculates the shortest movement cost from the
        start hub to every accessible hub. When multiple predecessors
        produce the same minimum cost, all of them are stored so that
        every minimum-cost path can later be reconstructed.
        Returns:
            A tuple containing the predecessor dictionary and the
            movement cost dictionary for all hubs.
        """
        costs = {}
        previous = {}
        pending: list[Hub] = []
        for hub in self.map.hubs.values():
            if hub == self.map.get_start_hub():
                costs[hub.name] = 0
            else:
                costs[hub.name] = float("inf")
            previous[hub.name] = []
            pending.append(hub)
        while pending != []:
            min_cost = float("inf")
            current: None | Hub = None
            for hub in pending:
                if min_cost > costs[hub.name]:
                    min_cost = costs[hub.name]
                    current = hub
            if current is None:
                break
            for neighbour in current.get_accessible_hubs():
                new_cost = costs[current.name]
                if neighbour.zone_type == "normal" or neighbour.zone_type == "priority":
                    new_cost += 1
                elif neighbour.zone_type == "restricted":
                    new_cost += 2
                if new_cost < costs[neighbour.name]:
                    costs[neighbour.name] = new_cost
                    previous[neighbour.name] = [current]
                elif new_cost == costs[neighbour.name]:
                    previous[neighbour.name].append(current)
            pending.remove(current)
        return previous, costs
